### ISSUE TITLE
Account Creation Epic

### ISSUE THREAD

**Issue by jkyan1988** [chingu-voyages/v43-tier3-team-41#27]
**__Feature Description__**
This epic is intended for users to create an account to be able to access website features by signing in, being able to log out, purchasing an item, processing payment and shipment details and creating profile, modify any information pertaining to an account. 

**__Major User Stories/tasks__**

- [ ] As a user, I want to sign up for an account so I can access full site features such as be able to add items to cart, checkout, access to add reviews, products, favorites, and access own profile.
- [ ] As a user, I want to be able to log into the website with my email and password and be able to log out.
- [ ] As a user, I want to be able to create user profile and provide personal information such as address and payment info.
- [ ] As a user, I want to be able to modify and customize my user profile.

**__Additional Considerations__**
- Depending on the information provided in a profile, we can add more details, profile pic, location, bio, be able to edit reviews, have a collection of reviews from user profile, as needed.
- Could add edit past orders (probably stretch goal) or re order same order, see history of orders?
- Backend database will have full CRUD features for user schemas as well as have validations for users to access.
- Frontend should be able to edit and post data to backend.
