### ISSUE TITLE
Search Page Epic

### ISSUE THREAD

**Issue by Katherine-KM** [chingu-voyages/v43-tier3-team-41#54]
- [x] As a user, I want to be able to search for products so that I can quickly find what I'm looking for.
- [x] As a user, I want to see relevant results displayed in an organized manner so that I can easily evaluate my options.
- [x] As a user, I want to be able to filter products displayed to quickly find what I am looking for.
